export const AUDIT_ACTIONS = {
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_REGISTER: "AUTH_REGISTER",
  AUTH_PASSWORD_CHANGE: "AUTH_PASSWORD_CHANGE",
  AUTH_REFRESH: "AUTH_REFRESH",
  AUTH_ACCESS_DENIED: "AUTH_ACCESS_DENIED",

  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_STATUS_CHANGED: "USER_STATUS_CHANGED",

  BOOK_CREATED: "BOOK_CREATED",
  BOOK_UPDATED: "BOOK_UPDATED",
  BOOK_DELETED: "BOOK_DELETED",
  BOOK_COPY_CREATED: "BOOK_COPY_CREATED",
  BOOK_COPY_UPDATED: "BOOK_COPY_UPDATED",
  BOOK_COPY_DELETED: "BOOK_COPY_DELETED",
  MEMBER_CREATED: "MEMBER_CREATED",
  MEMBER_UPDATED: "MEMBER_UPDATED",
  MEMBER_DELETED: "MEMBER_DELETED",

  ISSUE_CREATED: "ISSUE_CREATED",
  ISSUE_UPDATED: "ISSUE_UPDATED",
  ISSUE_RETURNED: "ISSUE_RETURNED",
  ISSUE_RENEWED: "ISSUE_RENEWED",
  ISSUE_DELETED: "ISSUE_DELETED",
  FINE_CREATED: "FINE_CREATED",
  FINE_UPDATED: "FINE_UPDATED",
  FINE_PAID: "FINE_PAID",
  FINE_WAIVED: "FINE_WAIVED",
  FINE_DELETED: "FINE_DELETED",

  RESERVATION_CREATED: "RESERVATION_CREATED",
  RESERVATION_UPDATED: "RESERVATION_UPDATED",
  RESERVATION_CANCELLED: "RESERVATION_CANCELLED",
  RESERVATION_READY: "RESERVATION_READY",
  RESERVATION_FULFILLED: "RESERVATION_FULFILLED",
  RESERVATION_EXPIRED: "RESERVATION_EXPIRED",
  RESERVATION_DELETED: "RESERVATION_DELETED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export type AuditResourceType =
  | "AUTH"
  | "USER"
  | "BOOK"
  | "BOOK_COPY"
  | "MEMBER"
  | "ISSUE"
  | "FINE"
  | "RESERVATION";
