export const PERMISSIONS = {
  // User Management
  USER_CREATE: "USER_CREATE",
  USER_READ: "USER_READ",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_MANAGE_ROLES: "USER_MANAGE_ROLES",

  // Library Management
  BOOK_CREATE: "BOOK_CREATE",
  BOOK_READ: "BOOK_READ",
  BOOK_UPDATE: "BOOK_UPDATE",
  BOOK_DELETE: "BOOK_DELETE",

  BOOK_COPY_CREATE: "BOOK_COPY_CREATE",
  BOOK_COPY_READ: "BOOK_COPY_READ",
  BOOK_COPY_UPDATE: "BOOK_COPY_UPDATE",
  BOOK_COPY_DELETE: "BOOK_COPY_DELETE",

  // Members
  MEMBER_CREATE: "MEMBER_CREATE",
  MEMBER_READ: "MEMBER_READ",
  MEMBER_UPDATE: "MEMBER_UPDATE",
  MEMBER_DELETE: "MEMBER_DELETE",

  // Circulation
  BOOK_ISSUE: "BOOK_ISSUE",
  BOOK_RETURN: "BOOK_RETURN",
  BOOK_RENEW: "BOOK_RENEW",

  // Reservations
  RESERVATION_CREATE: "RESERVATION_CREATE",
  RESERVATION_READ: "RESERVATION_READ",
  RESERVATION_UPDATE: "RESERVATION_UPDATE",
  RESERVATION_CANCEL: "RESERVATION_CANCEL",

  // Fines
  FINE_CREATE: "FINE_CREATE",
  FINE_READ: "FINE_READ",
  FINE_UPDATE: "FINE_UPDATE",
  FINE_WAIVE: "FINE_WAIVE",

  // Reports
  REPORT_VIEW: "REPORT_VIEW",
  REPORT_EXPORT: "REPORT_EXPORT",

  // Administration
  LIBRARY_SETTINGS: "LIBRARY_SETTINGS",
  AUDIT_LOG_VIEW: "AUDIT_LOG_VIEW",
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];