import { ROLES, Role } from "./roles.js";
import { PERMISSIONS, Permission } from "./permissions.js";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.LIBRARY_ADMIN]: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,

    PERMISSIONS.BOOK_CREATE,
    PERMISSIONS.BOOK_READ,
    PERMISSIONS.BOOK_UPDATE,
    PERMISSIONS.BOOK_DELETE,

    PERMISSIONS.BOOK_COPY_CREATE,
    PERMISSIONS.BOOK_COPY_READ,
    PERMISSIONS.BOOK_COPY_UPDATE,
    PERMISSIONS.BOOK_COPY_DELETE,

    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEMBER_DELETE,

    PERMISSIONS.BOOK_ISSUE,
    PERMISSIONS.BOOK_RETURN,
    PERMISSIONS.BOOK_RENEW,

    PERMISSIONS.RESERVATION_CREATE,
    PERMISSIONS.RESERVATION_READ,
    PERMISSIONS.RESERVATION_UPDATE,
    PERMISSIONS.RESERVATION_CANCEL,

    PERMISSIONS.FINE_CREATE,
    PERMISSIONS.FINE_READ,
    PERMISSIONS.FINE_UPDATE,
    PERMISSIONS.FINE_WAIVE,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,

    PERMISSIONS.LIBRARY_SETTINGS,
    PERMISSIONS.AUDIT_LOG_VIEW,
  ],

  [ROLES.LIBRARIAN]: [
    PERMISSIONS.BOOK_CREATE,
    PERMISSIONS.BOOK_READ,
    PERMISSIONS.BOOK_UPDATE,

    PERMISSIONS.BOOK_COPY_CREATE,
    PERMISSIONS.BOOK_COPY_READ,
    PERMISSIONS.BOOK_COPY_UPDATE,

    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE,

    PERMISSIONS.BOOK_ISSUE,
    PERMISSIONS.BOOK_RETURN,
    PERMISSIONS.BOOK_RENEW,

    PERMISSIONS.RESERVATION_CREATE,
    PERMISSIONS.RESERVATION_READ,
    PERMISSIONS.RESERVATION_UPDATE,
    PERMISSIONS.RESERVATION_CANCEL,

    PERMISSIONS.FINE_CREATE,
    PERMISSIONS.FINE_READ,
    PERMISSIONS.FINE_UPDATE,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
  ],

  [ROLES.ASSISTANT_LIBRARIAN]: [
    PERMISSIONS.BOOK_READ,
    PERMISSIONS.BOOK_COPY_READ,

    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE,

    PERMISSIONS.BOOK_ISSUE,
    PERMISSIONS.BOOK_RETURN,
    PERMISSIONS.BOOK_RENEW,

    PERMISSIONS.RESERVATION_CREATE,
    PERMISSIONS.RESERVATION_READ,

    PERMISSIONS.FINE_READ,

    PERMISSIONS.REPORT_VIEW,
  ],

  [ROLES.FACULTY]: [
    PERMISSIONS.BOOK_READ,
    PERMISSIONS.MEMBER_READ,

    PERMISSIONS.BOOK_ISSUE,
    PERMISSIONS.BOOK_RETURN,
    PERMISSIONS.BOOK_RENEW,

    PERMISSIONS.RESERVATION_CREATE,
    PERMISSIONS.RESERVATION_READ,
    PERMISSIONS.RESERVATION_CANCEL,

    PERMISSIONS.FINE_READ,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.BOOK_READ,

    PERMISSIONS.BOOK_ISSUE,
    PERMISSIONS.BOOK_RETURN,
    PERMISSIONS.BOOK_RENEW,

    PERMISSIONS.RESERVATION_CREATE,
    PERMISSIONS.RESERVATION_READ,
    PERMISSIONS.RESERVATION_CANCEL,

    PERMISSIONS.FINE_READ,
  ],

  [ROLES.MEMBER]: [
    PERMISSIONS.BOOK_READ,

    PERMISSIONS.BOOK_ISSUE,
    PERMISSIONS.BOOK_RETURN,
    PERMISSIONS.BOOK_RENEW,

    PERMISSIONS.RESERVATION_CREATE,
    PERMISSIONS.RESERVATION_READ,
    PERMISSIONS.RESERVATION_CANCEL,

    PERMISSIONS.FINE_READ,
  ],

  [ROLES.AUDITOR]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.BOOK_READ,
    PERMISSIONS.BOOK_COPY_READ,
    PERMISSIONS.MEMBER_READ,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,

    PERMISSIONS.AUDIT_LOG_VIEW,
  ],
};