export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  LIBRARY_ADMIN: "LIBRARY_ADMIN",
  LIBRARIAN: "LIBRARIAN",
  ASSISTANT_LIBRARIAN: "ASSISTANT_LIBRARIAN",
  FACULTY: "FACULTY",
  STUDENT: "STUDENT",
  MEMBER: "MEMBER",
  AUDITOR: "AUDITOR",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];